<?php

namespace Landmarx\Renderer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-11 at 16:33:49.
 */
class RendererTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Renderer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Renderer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Landmarx\Renderer\Renderer::getCharset
     * @todo   Implement testGetCharset().
     */
    public function testGetCharset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Landmarx\Renderer\Renderer::setCharset
     * @todo   Implement testSetCharset().
     */
    public function testSetCharset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}